
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Thu Jun 09 01:29:01 EEST 2022
//----------------------------------------------------

package _parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int StartSubtasks = 3;
  public static final int Word = 6;
  public static final int EOF = 0;
  public static final int EndSubtasks = 4;
  public static final int OneWordRepeat = 7;
  public static final int error = 1;
  public static final int OnlyOnce = 5;
  public static final int RepeatEvery = 8;
  public static final int StartAt = 9;
  public static final int StartTask = 2;
}

