
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Mon Jun 06 21:05:47 EEST 2022
//----------------------------------------------------

package _parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int StartSubtasks = 3;
  public static final int RepeatKeyword = 5;
  public static final int Postpone = 11;
  public static final int Word = 7;
  public static final int EOF = 0;
  public static final int EndSubtasks = 4;
  public static final int OneWordRepeat = 8;
  public static final int error = 1;
  public static final int OnlyOnce = 6;
  public static final int RepeatEvery = 9;
  public static final int StartAt = 10;
  public static final int StartTask = 2;
}

